"use client";
import React, { useState, useEffect } from 'react';
import { Navbar } from '../../components/Navbar';
import { TrytetClient, TetExecutionResult } from '@trytet/client';
import { Play, AlertCircle, ShieldCheck } from 'lucide-react';

export default function UncrashableDemo() {
  const [isRunning, setIsRunning] = useState(false);
  const [demoType, setDemoType] = useState<'standard' | 'trytet'>('trytet');
  const [logs, setLogs] = useState<string[]>([]);
  const [result, setResult] = useState<TetExecutionResult | null>(null);
  const [wasmBytes, setWasmBytes] = useState<Uint8Array | null>(null);

  useEffect(() => {
    // Preload the infinite loop Wasm binary
    fetch('/infinite-loop.wasm')
      .then(res => res.arrayBuffer())
      .then(buffer => setWasmBytes(new Uint8Array(buffer)))
      .catch(err => console.error("Failed to load wasm", err));
  }, []);

  const addLog = (msg: string) => {
    setLogs(prev => [...prev, `[${new Date().toISOString().split('T')[1].slice(0, -1)}] ${msg}`]);
  };

  const runDemo = async () => {
    if (!wasmBytes) return;
    setIsRunning(true);
    setLogs([]);
    setResult(null);

    addLog(`Initiating execution of unverified LLM generated script...`);

    if (demoType === 'standard') {
        addLog(`Spinning up standard Docker/Python subprocess...`);
        addLog(`Executing logic loop...`);
        
        // Simulate a complete freeze/crash that typical agent frameworks experience
        let dots = 0;
        const interval = setInterval(() => {
            dots++;
            setLogs(prev => {
                const newLogs = [...prev];
                newLogs[newLogs.length - 1] = `[${new Date().toISOString().split('T')[1].slice(0, -1)}] Executing logic loop` + '.'.repeat(dots);
                return newLogs;
            });
            if (dots > 10) {
                clearInterval(interval);
                addLog(`CRITICAL ERROR: Max Call Stack Size Exceeded / OOM`);
                addLog(`Host Application crashed. Agent state lost.`);
                setIsRunning(false);
            }
        }, 300);
        return;
    }

    if (demoType === 'trytet') {
        addLog(`Spinning up Trytet Wasm Component Sandbox...`);
        addLog(`Allocating deterministic fuel budget: 1,000,000 instructions.`);
        
        try {
            const client = new TrytetClient({ baseUrl: process.env.NEXT_PUBLIC_TRYTET_API_URL || 'http://localhost:3000' });
            
            const startTime = Date.now();
            
            const res = await client.execute({
                payload: Array.from(wasmBytes),
                allocated_fuel: 1_000_000,
                max_memory_mb: 32,
                alias: 'demo-agent',
            });
            
            const elapsed = Date.now() - startTime;
            
            addLog(`Execution completed in ${elapsed}ms (Engine Trapped).`);
            setResult(res);
            
            if (res.status === 'OutOfFuel') {
                addLog(`SUCCESS: Trytet deterministically trapped the infinite loop!`);
                addLog(`Unused compute refunded. Host application remains entirely safe.`);
            }
        } catch (err: unknown) {
            if (err instanceof Error) {
                addLog(`Error connecting to local Trytet engine: ${err.message}`);
            } else {
                addLog(`Error connecting to local Trytet engine: ${String(err)}`);
            }
        } finally {
            setIsRunning(false);
        }
    }
  };

  return (
    <div className="flex flex-col min-h-screen relative bg-[var(--bg-main)] text-[var(--text-main)]">
      <Navbar />
      
      <main className="flex-1 w-full max-w-5xl mx-auto pt-24 px-6 pb-24">
        <div className="mb-12">
            <h1 className="text-4xl font-bold mb-4">The <span className="text-[var(--electric-blue)]">"Uncrashable"</span> Demo</h1>
            <p className="text-lg text-[var(--text-sub)] max-w-2xl">
                LLMs hallucinate code. If you execute that code in a standard container or subprocess, your agent framework will crash. Trytet uses instruction-level fuel metering to trap runaway logic in microseconds.
            </p>
        </div>
        
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          
          <div className="flex flex-col gap-6">
            <div className="bg-[var(--bg-sub)] border border-[var(--card-border)] rounded-lg p-6">
                <h2 className="text-xl font-semibold mb-4">The Payload: Infinite Loop</h2>
                <p className="text-sm text-[var(--text-sub)] mb-4">
                    This is a WebAssembly module containing a tight, infinite cyclic branch. It represents a hallucinated `while(true)` loop generated by an LLM tool call.
                </p>
                <pre className="bg-[#0a0a0a] text-[var(--mint-success)] p-4 rounded border border-[var(--card-border)] overflow-x-auto text-sm font-mono">
{`(module
  (memory (export "memory") 1)
  (func (export "_start")
    (loop $inf (br $inf))
  )
)`}
                </pre>
            </div>

            <div className="bg-[var(--bg-sub)] border border-[var(--card-border)] rounded-lg p-6">
                <h2 className="text-xl font-semibold mb-4">Execution Environment</h2>
                
                <div className="flex gap-4 mb-6">
                    <button 
                        onClick={() => setDemoType('standard')}
                        className={`flex-1 py-3 px-4 rounded-md border flex items-center justify-center gap-2 transition-all ${demoType === 'standard' ? 'bg-red-900/20 border-red-500 text-red-200' : 'border-[var(--card-border)] text-[var(--text-sub)] hover:border-red-500/50'}`}
                    >
                        <AlertCircle size={18} />
                        Standard Process
                    </button>
                    <button 
                        onClick={() => setDemoType('trytet')}
                        className={`flex-1 py-3 px-4 rounded-md border flex items-center justify-center gap-2 transition-all ${demoType === 'trytet' ? 'bg-[var(--electric-blue)]/20 border-[var(--electric-blue)] text-[var(--electric-blue)]' : 'border-[var(--card-border)] text-[var(--text-sub)] hover:border-[var(--electric-blue)]/50'}`}
                    >
                        <ShieldCheck size={18} />
                        Trytet Engine
                    </button>
                </div>

                <button 
                    onClick={runDemo} 
                    disabled={isRunning || !wasmBytes}
                    className={`w-full font-bold py-4 px-6 rounded-md flex items-center justify-center gap-2 transition-all ${demoType === 'trytet' ? 'bg-[var(--electric-blue)] hover:bg-blue-600 text-white' : 'bg-red-600 hover:bg-red-700 text-white'} disabled:opacity-50 disabled:cursor-not-allowed`}
                >
                    <Play size={20} />
                    {isRunning ? 'Executing...' : 'Run Agent Payload'}
                </button>
            </div>
          </div>

          {/* Right Column: Terminal Output */}
          <div className="flex flex-col">
            <div className="bg-[#0a0a0a] border border-[var(--card-border)] rounded-lg h-full flex flex-col overflow-hidden">
                <div className="bg-[var(--bg-sub)] px-4 py-2 border-b border-[var(--card-border)] flex items-center gap-2">
                    <div className="w-3 h-3 rounded-full bg-red-500"></div>
                    <div className="w-3 h-3 rounded-full bg-yellow-500"></div>
                    <div className="w-3 h-3 rounded-full bg-green-500"></div>
                    <span className="text-xs text-[var(--text-sub)] ml-2 font-mono">Host Application Console</span>
                </div>
                
                <div className="p-4 flex-1 overflow-y-auto font-mono text-sm leading-relaxed whitespace-pre-wrap flex flex-col gap-1">
                    {logs.length === 0 ? (
                        <div className="text-[var(--code-comment)] italic">Waiting for execution...</div>
                    ) : (
                        logs.map((log, i) => (
                            <div key={i} className={
                                log.includes('CRITICAL ERROR') || log.includes('crashed') ? 'text-red-400' :
                                log.includes('SUCCESS') ? 'text-[var(--mint-success)]' :
                                log.includes('Error') ? 'text-red-400' :
                                'text-gray-300'
                            }>
                                {log}
                            </div>
                        ))
                    )}

                    {result && demoType === 'trytet' && (
                        <div className="mt-6 border border-[var(--card-border)] rounded bg-[var(--bg-sub)] p-4 text-gray-300">
                            <div className="font-bold text-[var(--electric-blue)] mb-2">Trytet Interception Report</div>
                            <div className="grid grid-cols-2 gap-2 text-xs">
                                <div><span className="text-[var(--text-sub)]">Engine Status:</span> <span className="text-[var(--magenta-teleport)] font-bold">{typeof result.status === 'string' ? result.status : JSON.stringify(result.status)}</span></div>
                                <div><span className="text-[var(--text-sub)]">Duration:</span> {result.execution_duration_us} µs</div>
                                <div><span className="text-[var(--text-sub)]">Fuel Burned:</span> {result.fuel_consumed.toLocaleString()} ops</div>
                                <div><span className="text-[var(--text-sub)]">Refunded:</span> {(1000000 - result.fuel_consumed).toLocaleString()} ops</div>
                            </div>
                        </div>
                    )}
                </div>
            </div>
          </div>

        </div>
      </main>
    </div>
  );
}
